/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json


/**
 *
 *
 * @param mscnumber The identifier of a billing unit defined by the MSC.
 * @param pmnumber The identifier of a billing unit defined by the propertymanagement.
 */

@Serializable
data class BillingUnitReference(

    /* The identifier of a billing unit defined by the MSC. */
    @SerialName("mscnumber")
    val mscnumber: kotlin.String,

    /* The identifier of a billing unit defined by the propertymanagement. */
    @SerialName("pmnumber")
    val pmnumber: kotlin.String? = null

) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is BillingUnitReference) return false
        return other.mscnumber == mscnumber
    }

    override fun hashCode(): Int {
        return mscnumber.hashCode()
    }

    override fun toString(): String {
        val prettyJson = Json { // this returns the JsonBuilder
            prettyPrint = true
            // optional: specify indent
            prettyPrintIndent = " "
        }
        return prettyJson.encodeToString(this)
    }

}

