/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Describes available data for a consumption period.
 *
 * @param period Identifier of a consumption period with year and month.
 * @param update The timestamp of the last data update for this period.
 */

@Serializable
data class ConsumptionSummaryPeriod (

    /* Identifier of a consumption period with year and month. */
    @SerialName("period")
    val period: String,

    /* The timestamp of the last data update for this period. */
    @SerialName("update")
    val update: String

) {


}

