/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.BillingUnitReference
import org.openapitools.client.models.ConsumptionSummaryPeriod

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Summary of available consumption data for a billing unit.
 *
 * @param reference 
 * @param periods Overview of available consumption periods and their last update.
 */

@Serializable
data class ConsumptionSummaryBillingUnit (

    @SerialName("reference")
    val reference: BillingUnitReference,

    /* Overview of available consumption periods and their last update. */
    @SerialName("periods")
    val periods: kotlin.collections.List<ConsumptionSummaryPeriod>

) {


}

