/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.openapitools.client.models.BillingUnitReference
import org.openapitools.client.models.ConsumptionDataResidentialUnit

/**
 * Consumption data for a billing unit and specific period.
 *
 * @param reference 
 * @param period Identifier of a consumption period with year and month.
 * @param residentialunits List of consumption data on residential unit level.
 */

@Serializable
data class ConsumptionDataBillingUnit (

    @SerialName("reference")
    val reference: BillingUnitReference,

    /* Identifier of a consumption period with year and month. */
    @SerialName("period")
    val period: kotlin.String,

    /* List of consumption data on residential unit level. */
    @SerialName("residentialunits")
    val residentialunits: kotlin.collections.List<ConsumptionDataResidentialUnit>

) {
    override fun toString(): String {
        val prettyJson = Json { // this returns the JsonBuilder
            prettyPrint = true
            // optional: specify indent
            prettyPrintIndent = " "
        }
        return prettyJson.encodeToString(this)
    }

}

