/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Status of a residential unit:  * `PARTLY_ESTIMATED`: consumption is partly based on estimated values * `INCOMPLETE`: consumption cannot be calculated because of incomplete reading values - e.g. first month after installation of meters * `NO_RADIO_EQUIPMENT`: Residential unit is not equipped with radio equipment or radio is not enabled * `IMPLAUSIBLE_VALUES`: the values are obviously implausible to calculate consumption values * `CALC_NOT_POSSIBLE`: further reasons that calculation is not possible * `ERROR`: further unspecified errors 
 *
 * Values: PARTLY_ESTIMATED,INCOMPLETE,NO_RADIO_EQUIPMENT,IMPLAUSIBLE_VALUES,CALC_NOT_POSSIBLE,ERROR
 */

@Serializable
enum class RemarkCodeListResidentialUnitEntry(val value: kotlin.String) {

    @SerialName("PARTLY_ESTIMATED")
    PARTLY_ESTIMATED("PARTLY_ESTIMATED"),

    @SerialName("INCOMPLETE")
    INCOMPLETE("INCOMPLETE"),

    @SerialName("NO_RADIO_EQUIPMENT")
    NO_RADIO_EQUIPMENT("NO_RADIO_EQUIPMENT"),

    @SerialName("IMPLAUSIBLE_VALUES")
    IMPLAUSIBLE_VALUES("IMPLAUSIBLE_VALUES"),

    @SerialName("CALC_NOT_POSSIBLE")
    CALC_NOT_POSSIBLE("CALC_NOT_POSSIBLE"),

    @SerialName("ERROR")
    ERROR("ERROR");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value
}

