/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Status of a billing unit:  * `NO_CONTRACT`: no valid contract for consumptions for this billing unit * `NO_RADIO_EQUIPMENT`: Billing unit is not equipped with radio equipment * `ERROR`: further unspecified errors 
 *
 * Values: NO_CONTRACT,NO_RADIO_EQUIPMENT,ERROR
 */

@Serializable
enum class RemarkCodeListBillingUnitEntry(val value: kotlin.String) {

    @SerialName("NO_CONTRACT")
    NO_CONTRACT("NO_CONTRACT"),

    @SerialName("NO_RADIO_EQUIPMENT")
    NO_RADIO_EQUIPMENT("NO_RADIO_EQUIPMENT"),

    @SerialName("ERROR")
    ERROR("ERROR");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value
}

