/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The service a consumption value is related to:  * `HEATING` * `HOT_WATER` * `COOLING` * `COLD_WATER` 
 *
 * Values: HEATING,HOT_WATER,COOLING,COLD_WATER
 */

@Serializable
enum class Service(val value: kotlin.String) {

    @SerialName("HEATING")
    HEATING("HEATING"),

    @SerialName("HOT_WATER")
    HOT_WATER("HOT_WATER"),

    @SerialName("COOLING")
    COOLING("COOLING"),

    @SerialName("COLD_WATER")
    COLD_WATER("COLD_WATER");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value
}

